# Generated by Django 5.2.17 on 2026-09-23 18:27

from typing import ClassVar

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import app.accounts.managers


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar[list] = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("players", "0001_initial"),
        ("teams", "0001_initial"),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name="email address"),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[("de", "Deutsch"), ("en", "English")],
                        default="de",
                        max_length=8,
                        verbose_name="preferred language",
                    ),
                ),
                (
                    "preferred_theme",
                    models.CharField(
                        choices=[("auto", "Auto"), ("light", "Light"), ("dark", "Dark")],
                        default="auto",
                        max_length=8,
                        verbose_name="preferred theme",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "player_link",
                    models.OneToOneField(
                        blank=True,
                        help_text="Optional: lets a Player-role user see their own penalties.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_account",
                        to="players.player",
                        verbose_name="linked player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required for Captain role; ignored for Admin.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="teams.team",
                        verbose_name="team",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
            managers=[
                ("objects", app.accounts.managers.UserManager()),
            ],
        ),
    ]
