# Generated by Django 5.2.17 on 2026-09-25 06:30

from typing import ClassVar

from django.db import migrations, models


def approve_existing_users(apps, schema_editor):
    """Accounts that existed BEFORE the approval workflow keep their access.

    Only self-registrations created after this migration start as "pending".
    """
    user_model = apps.get_model("accounts", "User")
    user_model.objects.filter(approval_status="pending").update(approval_status="approved")


def backfill_verified_emails(apps, schema_editor):
    """Give every pre-existing account a VERIFIED allauth e-mail address.

    ``ACCOUNT_EMAIL_VERIFICATION = "mandatory"`` would otherwise block the
    first login of every account created before django-allauth was introduced.
    """
    user_model = apps.get_model("accounts", "User")
    email_model = apps.get_model("account", "EmailAddress")
    for user in user_model.objects.all().iterator():
        email_model.objects.get_or_create(
            user=user,
            email=user.email,
            defaults={"verified": True, "primary": True},
        )


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("accounts", "0001_initial"),
        # django-allauth: EmailAddress table must exist for the backfill.
        ("account", "0009_emailaddress_unique_primary_email"),
    ]

    operations: ClassVar[list] = [
        migrations.AddField(
            model_name="user",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                help_text="Pending users cannot log in until an admin approves them.",
                max_length=16,
                verbose_name="approval status",
            ),
        ),
        migrations.RunPython(approve_existing_users, migrations.RunPython.noop, elidable=True),
        migrations.RunPython(backfill_verified_emails, migrations.RunPython.noop, elidable=True),
    ]
