# Generated by Django 5.2.17 on 2026-09-28 08:49

from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("accounts", "0002_user_approval_status"),
        ("teams", "0001_initial"),
    ]

    operations: ClassVar[list] = [
        migrations.AlterField(
            model_name="user",
            name="team",
            field=models.ForeignKey(
                blank=True,
                # Optional captaincy (role-decoupled): a Captain may have no
                # team, an Admin may additionally captain one team.
                help_text="Optional captaincy: the team this account leads. Allowed for Captain and Admin.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="teams.team",
                verbose_name="team",
            ),
        ),
    ]
