# Generated by Django 5.2.17 on 2026-09-30 16:15

from typing import ClassVar

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("accounts", "0003_alter_user_team"),
        ("players", "0003_playerteam_alter_player_teams_and_more"),
        ("teams", "0001_initial"),
    ]

    operations: ClassVar[list] = [
        migrations.AlterField(
            model_name="user",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("requested", "Invited"),
                ],
                db_index=True,
                default="pending",
                help_text="Pending users cannot log in until an admin approves them.",
                max_length=16,
                verbose_name="approval status",
            ),
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        help_text="Single-use acceptance token — blanked on acceptance, regenerated on resend.",
                        max_length=64,
                        unique=True,
                        verbose_name="token",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("Admin", "Admin"), ("Captain", "Captain"), ("Player", "Player")],
                        default="Player",
                        max_length=16,
                        verbose_name="role",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="invited at")),
                ("expires_at", models.DateTimeField(db_index=True, verbose_name="expires at")),
                (
                    "accepted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="accepted at"),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invited_accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="invited by",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pre-assigned player — linked to the user on acceptance.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations",
                        to="players.player",
                        verbose_name="player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional captaincy pre-assignment — only valid for Captain/Admin.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations",
                        to="teams.team",
                        verbose_name="team",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitation",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "invitation",
                "verbose_name_plural": "invitations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["accepted_at", "expires_at"], name="accounts_in_accepte_cb8a88_idx"
                    )
                ],
            },
        ),
    ]
