# Generated by Django 5.2.17 on 2026-10-01 05:00

import datetime
from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("accounts", "0004_alter_user_approval_status_invitation"),
    ]

    operations: ClassVar[list] = [
        migrations.AddField(
            model_name="user",
            name="club_news_optin",
            field=models.BooleanField(
                default=True,
                help_text="Round mails / club information from your club.",
                verbose_name="club news",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="penalty_notify_mode",
            field=models.CharField(
                choices=[
                    ("off", "Off"),
                    ("immediate", "Quick (collected)"),
                    ("daily", "Daily digest"),
                ],
                default="daily",
                help_text="When newly assigned penalties are e-mailed to you.",
                max_length=16,
                verbose_name="penalty notifications",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="penalty_notify_time",
            field=models.TimeField(
                default=datetime.time(8, 0),
                help_text="Only used by the daily digest.",
                verbose_name="digest time",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="repayment_notify",
            field=models.BooleanField(
                default=True,
                help_text="One e-mail per recorded repayment (receipt).",
                verbose_name="payment confirmations",
            ),
        ),
    ]
