# Generated by Django 5.2.17 on 2026-10-01 07:33

from typing import ClassVar

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="TeamCashier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "user_label",
                    models.CharField(
                        blank=True,
                        help_text="Display name at assignment time — survives account deletion.",
                        max_length=255,
                        verbose_name="cashier (snapshot)",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, verbose_name="valid from"
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="valid to"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cashiers",
                        to="teams.team",
                        verbose_name="team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cashier_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="cashier",
                    ),
                ),
            ],
            options={
                "verbose_name": "cashier assignment",
                "verbose_name_plural": "cashier assignments",
                "ordering": ["team__name", "-valid_from"],
                "indexes": [
                    models.Index(fields=["team", "valid_to"], name="teams_teamc_team_id_b453cf_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("valid_to__isnull", True)),
                        fields=("team",),
                        name="teamcashier_one_open_per_team",
                    )
                ],
            },
        ),
    ]
