# Generated by Django 5.2.17 on 2026-10-01 05:00

from typing import ClassVar

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar[list] = [
        ("penalties", "0008_penaltycatalogitem_affects_both_players"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="NotificationOutbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Snapshot at queue time — the audit trail keeps the original target.",
                        max_length=254,
                        verbose_name="e-mail address",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        help_text="Recipient language at queue time (rendering must not depend on a request).",
                        max_length=8,
                        verbose_name="language",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        db_index=True,
                        default="penalty_created",
                        help_text="Template family of the queued message.",
                        max_length=32,
                        verbose_name="kind",
                    ),
                ),
                (
                    "queued_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="queued at"
                    ),
                ),
                (
                    "send_after",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Coalescing deadline (quick mode) or the next digest time.",
                        verbose_name="send after",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = pending; set BEFORE delivery as the flush claim.",
                        null=True,
                        verbose_name="sent at",
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0, verbose_name="attempts")),
                ("last_error", models.TextField(blank=True, verbose_name="last error")),
                (
                    "penalties",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Soft-deleted rows are dropped when the batch is flushed.",
                        related_name="outbox_entries",
                        to="penalties.penalty",
                        verbose_name="penalties",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_outbox",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "queued notification",
                "verbose_name_plural": "queued notifications",
                "ordering": ["send_after", "id"],
                "indexes": [
                    models.Index(
                        fields=["sent_at", "send_after"], name="app_notific_sent_at_4b1bbb_idx"
                    )
                ],
            },
        ),
    ]
