# Generated by Django 5.2.17 on 2026-09-23 18:36

from typing import ClassVar

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar[list] = [
        ("matchdays", "0001_initial"),
        ("players", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="PenaltyCatalogItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("description", models.CharField(max_length=255, verbose_name="description")),
                (
                    "amount_eur",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="amount (EUR)"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("PER_ALL_OTHER_MATCHDAY_PLAYERS", "Per all other matchday players"),
                        ],
                        default="NORMAL",
                        max_length=32,
                        verbose_name="type",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
            ],
            options={
                "verbose_name": "penalty catalog item",
                "verbose_name_plural": "penalty catalog items",
                "ordering": ["type", "description"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount_eur__gt", 0)),
                        name="catalog_item_amount_eur_positive",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Penalty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "description_snapshot",
                    models.CharField(max_length=255, verbose_name="description (snapshot)"),
                ),
                (
                    "amount_eur",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="amount (EUR)"
                    ),
                ),
                (
                    "group_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Shared by all rows of one group penalty.",
                        max_length=36,
                        null=True,
                        verbose_name="group id",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="deleted by",
                    ),
                ),
                (
                    "matchday",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="penalties",
                        to="matchdays.matchday",
                        verbose_name="matchday",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="penalties",
                        to="players.player",
                        verbose_name="player",
                    ),
                ),
                (
                    "catalog_item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="penalties.penaltycatalogitem",
                        verbose_name="catalog item",
                    ),
                ),
            ],
            options={
                "verbose_name": "penalty",
                "verbose_name_plural": "penalties",
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount_eur__gt", 0)),
                        name="penalty_amount_eur_positive",
                    )
                ],
            },
        ),
    ]
