# Generated by Django 5.2.17 on 2026-09-24 17:31

from typing import ClassVar

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("penalties", "0001_initial"),
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar[list] = [
        migrations.AddField(
            model_name="penalty",
            name="paid_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="paid at"
            ),
        ),
        migrations.AddField(
            model_name="penalty",
            name="paid_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="paid by",
            ),
        ),
        migrations.CreateModel(
            name="TeamCatalogAmount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "amount_eur",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="amount (EUR)"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "catalog_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_amounts",
                        to="penalties.penaltycatalogitem",
                        verbose_name="catalog item",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalog_amounts",
                        to="teams.team",
                        verbose_name="team",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "team catalog amount",
                "verbose_name_plural": "team catalog amounts",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("team", "catalog_item"), name="unique_team_catalog_amount"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount_eur__gt", 0)),
                        name="team_catalog_amount_eur_positive",
                    ),
                ],
            },
        ),
    ]
