# Generated by Django 5.2.17 on 2026-09-24 18:01

from typing import ClassVar

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("penalties", "0002_penalty_paid_at_penalty_paid_by_teamcatalogamount"),
        ("players", "0002_alter_player_options_and_more"),
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar[list] = [
        migrations.AlterField(
            model_name="penaltycatalogitem",
            name="type",
            field=models.CharField(
                choices=[
                    ("NORMAL", "Normal"),
                    ("PER_ALL_OTHER_MATCHDAY_PLAYERS", "Per all other matchday players"),
                    ("MANUAL", "Manual"),
                ],
                default="NORMAL",
                max_length=32,
                verbose_name="type",
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "amount_eur",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="amount (EUR)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="recorded by",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="players.player",
                        verbose_name="player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="teams.team",
                        verbose_name="team",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment",
                "verbose_name_plural": "payments",
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount_eur__gt", 0)),
                        name="payment_amount_eur_positive",
                    )
                ],
            },
        ),
    ]
