# Generated by Django 5.2.17 on 2026-09-24 18:03

from typing import ClassVar

from django.db import migrations


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("penalties", "0004_convert_paid_penalties_to_payments"),
    ]

    operations: ClassVar[list] = [
        migrations.RemoveField(
            model_name="penalty",
            name="paid_at",
        ),
        migrations.RemoveField(
            model_name="penalty",
            name="paid_by",
        ),
    ]
