# Generated by Django 5.2.17 on 2026-09-24 18:17

from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def backfill_seasons(apps, schema_editor):
    """Existing installs become ONE closed cash box.

    Every matchday and payment without a season is assigned to a single
    auto-named season (``YYYY/YYYY`` of the migration date). Fresh installs
    have no data here — ``bootstrap`` creates the first season instead.
    """
    Season = apps.get_model("matchdays", "Season")
    Matchday = apps.get_model("matchdays", "Matchday")
    Payment = apps.get_model("penalties", "Payment")
    if not Matchday.objects.exists() and not Payment.objects.exists():
        return
    year = timezone.now().year
    season, _created = Season.objects.get_or_create(name=f"{year}/{year + 1}")
    Matchday.objects.filter(season__isnull=True).update(season=season)
    Payment.objects.filter(season__isnull=True).update(season=season)


def keep_payments_as_is(apps, schema_editor):
    """No-op: Payment rows keep their season on reverse (column is dropped)."""


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("matchdays", "0002_season_matchday_season"),
        ("penalties", "0005_remove_penalty_paid_at_remove_penalty_paid_by"),
    ]

    operations: ClassVar[list] = [
        migrations.AddField(
            model_name="payment",
            name="season",
            field=models.ForeignKey(
                blank=True,
                help_text="Payments only reduce debt of the same season.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="matchdays.season",
                verbose_name="season",
            ),
        ),
        migrations.RunPython(backfill_seasons, keep_payments_as_is),
    ]
