# Generated by Django 5.2.17 on 2026-09-28
"""Per-team catalog config: active flag, drop the global active switch.

NOTE: the file name is kept from an earlier iteration ("nullable_amount")
so already-migrated test/livesystem databases — where this migration is
recorded under that name — stay compatible. ``amount_eur`` itself is NOT
altered here: the fee is required (always filled).

(a) ``TeamCatalogAmount`` gains the per-team ``active`` flag,
(b) data migration: every globally-inactive ``PenaltyCatalogItem`` gets an
    explicit ``active=False`` row for ALL existing teams, seeded with the
    item's default amount (preserves the current behaviour — active items
    need no rows: missing row = active),
(c) ``PenaltyCatalogItem.active`` (the global switch) is removed.
"""

from typing import ClassVar

from django.conf import settings
from django.db import migrations, models


def backfill_inactive_items_to_teams(apps, schema_editor):
    """Move the global "inactive" flag into per-team rows (step b above)."""
    PenaltyCatalogItem = apps.get_model("penalties", "PenaltyCatalogItem")
    TeamCatalogAmount = apps.get_model("penalties", "TeamCatalogAmount")
    Team = apps.get_model("teams", "Team")

    teams = list(Team.objects.all())
    for item in PenaltyCatalogItem.objects.filter(active=False):
        for team in teams:
            row = TeamCatalogAmount.objects.filter(catalog_item=item, team=team).first()
            if row is None:
                # Missing row: explicit inactive row seeded with the default fee.
                TeamCatalogAmount.objects.create(
                    catalog_item=item, team=team, active=False, amount_eur=item.amount_eur
                )
            elif not row.active:
                # Existing row: already carries an amount — just flag inactive.
                TeamCatalogAmount.objects.filter(pk=row.pk).update(active=False)


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("penalties", "0006_payment_season"),
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar[list] = [
        migrations.AddField(
            model_name="teamcatalogamount",
            name="active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.RunPython(
            backfill_inactive_items_to_teams,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="penaltycatalogitem",
            name="active",
        ),
    ]
