# Generated by Django 5.2.17 on 2026-09-30
"""Doubles (Doppelspiel): flag a catalog item as affecting both players.

``affects_both_players=True`` makes the penalty form offer an optional second
player (the doubles partner) — see ``PenaltyAssignForm.double_partner``.
"""

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("penalties", "0007_team_config_active_nullable_amount_drop_global_active"),
    ]

    operations: ClassVar[list] = [
        migrations.AddField(
            model_name="penaltycatalogitem",
            name="affects_both_players",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Offer the doubles partner when this penalty is assigned — "
                    "e.g. a low dart both players achieved together."
                ),
                verbose_name="Affects both doubles players?",
            ),
        ),
    ]
