# Generated by Django 5.2.17 on 2026-10-01 07:33
#
# UPGRADE-SAFE variant (review B1): the original one-step AddField added
# ``received_by`` as NOT NULL WITHOUT a backfill, which crashed `migrate` on
# every live database that already contained payment rows —
#   SQLite:      IntegrityError: NOT NULL constraint failed:
#                new__penalties_payment.received_by_id
#   PostgreSQL:  ERROR: column "received_by_id" contains null values
# and took the container down at boot (entrypoint.sh runs `set -e` ->
# `manage.py migrate`). The column is therefore added NULLABLE first, EXISTING
# rows are backfilled, and only then is the model's NOT NULL invariant
# enforced. Fresh installs (no rows) take the same path and stay green.

from typing import ClassVar

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_received_by(apps, schema_editor):
    """Give pre-existing payment rows a ``received_by`` snapshot.

    * ``created_by`` (the account that recorded the money) is the best
      historical answer available — payments made before the Kasse feature,
    * rows whose recorder was deleted fall back to any remaining account
      (superuser first — in practice the env-seeded bootstrap admin),
    * a database holding payments but NOT A SINGLE user account cannot be
      upgraded meaningfully; it fails with an actionable message instead of a
      cryptic IntegrityError halfway through the schema change.
    """
    Payment = apps.get_model("penalties", "Payment")
    User = apps.get_model("accounts", "User")

    Payment.objects.filter(received_by__isnull=True, created_by__isnull=False).update(
        received_by=models.F("created_by")
    )
    if not Payment.objects.filter(received_by__isnull=True).exists():
        return

    fallback = (
        User.objects.filter(is_superuser=True).order_by("pk").first()
        or User.objects.filter(is_active=True).order_by("pk").first()
        or User.objects.order_by("pk").first()
    )
    if fallback is None:
        raise RuntimeError(
            "penalties.0009: payment rows exist whose recorder (created_by) was "
            "deleted AND the database contains no user account to backfill "
            "received_by with. Restore a user account (e.g. run "
            "`manage.py bootstrap`) and re-run `manage.py migrate`."
        )
    Payment.objects.filter(received_by__isnull=True).update(received_by=fallback.pk)


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("penalties", "0008_penaltycatalogitem_affects_both_players"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar[list] = [
        # 1) Nullable first — safe on ANY existing data.
        migrations.AddField(
            model_name="payment",
            name="received_by",
            field=models.ForeignKey(
                help_text="The cashier who physically received the money (snapshot at record time).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="received_payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="received by",
            ),
            preserve_default=False,
        ),
        # 2) Existing rows: created_by, else a surviving account.
        migrations.RunPython(backfill_received_by, migrations.RunPython.noop),
        # 3) Now the model invariant (NOT NULL) can be enforced on every row.
        migrations.AlterField(
            model_name="payment",
            name="received_by",
            field=models.ForeignKey(
                help_text="The cashier who physically received the money (snapshot at record time).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="received_payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="received by",
            ),
        ),
    ]
