# Generated by Django 5.2.17 on 2026-10-01 07:33

from typing import ClassVar

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies: ClassVar[list] = [
        ("penalties", "0008_penaltycatalogitem_affects_both_players"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar[list] = [
        migrations.AddField(
            model_name="payment",
            name="received_by",
            field=models.ForeignKey(
                help_text="The cashier who physically received the money (snapshot at record time).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="received_payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="received by",
            ),
            preserve_default=False,
        ),
    ]
