# Generated by Django 5.2.17 on 2026-10-01 10:33

from typing import ClassVar

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("matchdays", "0003_season_is_default_season_teams"),
        ("penalties", "0009_payment_received_by"),
        ("players", "0003_playerteam_alter_player_teams_and_more"),
        ("teams", "0002_teamcashier"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar[list] = [
        migrations.RemoveConstraint(
            model_name="payment",
            name="payment_amount_eur_positive",
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_eur__gt", 0), ("amount_eur__lt", 0), _connector="OR"),
                name="payment_amount_eur_not_zero",
            ),
        ),
    ]
