# Generated by Django 5.2.17 on 2026-10-01 11:20

from typing import ClassVar

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("penalties", "0010_remove_payment_payment_amount_eur_positive_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar[list] = [
        migrations.AlterField(
            model_name="payment",
            name="received_by",
            field=models.ForeignKey(
                help_text="The cashier who physically received or paid out the money (snapshot at record time).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="received_payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="received by",
            ),
        ),
    ]
