# Generated by Django 5.2.17 on 2026-10-03

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("penalties", "0011_alter_payment_received_by"),
    ]

    operations: ClassVar[list] = [
        migrations.AlterField(
            model_name="penaltycatalogitem",
            name="type",
            field=models.CharField(
                choices=[
                    ("NORMAL", "Affects the player"),
                    ("PER_ALL_OTHER_MATCHDAY_PLAYERS", "Affects all other matchday players"),
                    ("MANUAL", "Affects the player – special penalty"),
                ],
                default="NORMAL",
                max_length=32,
                verbose_name="type",
            ),
        ),
    ]
