# Generated by Django 5.2.17 on 2026-09-23 18:27

from typing import ClassVar

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar[list] = [
        ("players", "0001_initial"),
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="Matchday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "opponent",
                    models.CharField(
                        help_text='Free text, e.g. "SV Eichenberg".',
                        max_length=255,
                        verbose_name="opponent",
                    ),
                ),
                (
                    "venue",
                    models.CharField(
                        choices=[("home", "Home"), ("away", "Away")],
                        default="home",
                        max_length=8,
                        verbose_name="venue",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="date")),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, verbose_name="description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matchdays",
                        to="teams.team",
                        verbose_name="team",
                    ),
                ),
            ],
            options={
                "verbose_name": "matchday",
                "verbose_name_plural": "matchdays",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MatchdayPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "matchday",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="matchdays.matchday",
                        verbose_name="matchday",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matchday_participations",
                        to="players.player",
                        verbose_name="player",
                    ),
                ),
            ],
            options={
                "verbose_name": "matchday player",
                "verbose_name_plural": "matchday players",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("matchday", "player"), name="unique_matchday_player"
                    )
                ],
            },
        ),
    ]
