# Generated by Django 5.2.17 on 2026-09-24 18:17

from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("matchdays", "0001_initial"),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Convention YYYY/YYYY, e.g. "2026/2027".',
                        max_length=32,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
            ],
            options={
                "verbose_name": "season",
                "verbose_name_plural": "seasons",
                "ordering": ["-name"],
            },
        ),
        migrations.AddField(
            model_name="matchday",
            name="season",
            field=models.ForeignKey(
                blank=True,
                help_text="Every matchday belongs to one season (a closed cash box).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matchdays",
                to="matchdays.season",
                verbose_name="season",
            ),
        ),
    ]
