# Generated by Django 5.2.17 on 2026-09-25 04:49

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("matchdays", "0002_season_matchday_season"),
        ("teams", "0001_initial"),
    ]

    operations: ClassVar[list] = [
        migrations.AddField(
            model_name="season",
            name="is_default",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="The default season is shown to every user who has not picked a season themselves. A personal choice in the navbar only lasts for the session and never changes this default.",
                verbose_name="default season",
            ),
        ),
        migrations.AddField(
            model_name="season",
            name="teams",
            field=models.ManyToManyField(
                blank=True,
                help_text="Only these teams are active in this season. Select no team to activate every team.",
                related_name="seasons",
                to="teams.team",
                verbose_name="teams",
            ),
        ),
    ]
