# Generated by Django 5.2.17 on 2026-09-23 18:28

from typing import ClassVar

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar[list] = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("team_created", "Team created"),
                            ("team_updated", "Team updated"),
                            ("team_deleted", "Team deleted"),
                            ("player_created", "Player created"),
                            ("player_updated", "Player updated"),
                            ("player_deactivated", "Player deactivated"),
                            ("matchday_created", "Matchday created"),
                            ("matchday_updated", "Matchday updated"),
                            ("matchday_deleted", "Matchday deleted"),
                            ("penalty_assigned", "Penalty assigned"),
                            ("penalty_edited", "Penalty edited"),
                            ("penalty_deleted", "Penalty deleted"),
                            ("user_created", "User created"),
                            ("user_updated", "User updated"),
                            ("user_deactivated", "User deactivated"),
                        ],
                        db_index=True,
                        max_length=64,
                        verbose_name="action",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(blank=True, max_length=120, verbose_name="target type"),
                ),
                (
                    "target_id",
                    models.PositiveBigIntegerField(blank=True, null=True, verbose_name="target id"),
                ),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="metadata")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "audit log entry",
                "verbose_name_plural": "audit log entries",
                "ordering": ["-created_at"],
            },
        ),
    ]
