# Generated by Django 5.2.17 on 2026-09-25 04:49

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("core", "0004_alter_auditlog_action"),
    ]

    operations: ClassVar[list] = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("team_created", "Team created"),
                    ("team_updated", "Team updated"),
                    ("team_deleted", "Team deleted"),
                    ("player_created", "Player created"),
                    ("player_updated", "Player updated"),
                    ("player_deactivated", "Player deactivated"),
                    ("matchday_created", "Matchday created"),
                    ("matchday_updated", "Matchday updated"),
                    ("matchday_deleted", "Matchday deleted"),
                    ("season_created", "Season created"),
                    ("season_updated", "Season updated"),
                    ("season_deleted", "Season deleted"),
                    ("penalty_assigned", "Penalty assigned"),
                    ("penalty_edited", "Penalty edited"),
                    ("penalty_deleted", "Penalty deleted"),
                    ("penalty_paid", "Penalty paid"),
                    ("penalty_payment_reverted", "Penalty payment reverted"),
                    ("payment_recorded", "Payment recorded"),
                    ("payment_deleted", "Payment reverted"),
                    ("user_created", "User created"),
                    ("user_updated", "User updated"),
                    ("user_deactivated", "User deactivated"),
                ],
                db_index=True,
                max_length=64,
                verbose_name="action",
            ),
        ),
    ]
