# Generated by Django 5.2.17 on 2026-09-24 16:56
#
# Player belongs to MULTIPLE teams now (Player.teams M2M replaces the single
# Player.team FK). Order matters: the new M2M table is created first, existing
# FK memberships are copied into it, and only then is the old column dropped —
# so existing (live) databases upgrade without data loss.

from typing import ClassVar

from django.db import migrations, models


def copy_team_to_teams(apps, schema_editor):
    """One membership row per existing FK value (historical models)."""
    Player = apps.get_model("players", "Player")
    for player in Player.objects.exclude(team=None).iterator():
        player.teams.add(player.team_id)


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("players", "0001_initial"),
        ("teams", "0001_initial"),
    ]

    operations: ClassVar[list] = [
        migrations.AlterModelOptions(
            name="player",
            options={
                "ordering": ["name"],
                "verbose_name": "player",
                "verbose_name_plural": "players",
            },
        ),
        migrations.RemoveIndex(
            model_name="player",
            name="players_pla_team_id_eb1bb0_idx",
        ),
        migrations.AddField(
            model_name="player",
            name="teams",
            field=models.ManyToManyField(
                help_text="A player can belong to multiple teams.",
                related_name="players",
                to="teams.team",
                verbose_name="teams",
            ),
        ),
        migrations.RunPython(copy_team_to_teams, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="player",
            name="team",
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(fields=["name"], name="players_pla_name_f5b1bf_idx"),
        ),
    ]
