# Players: the player <-> team assignment becomes SEASON-DEPENDENT.
#
# `Player.teams` is now an M2M through `PlayerTeam` (player, team, season).
# Django REFUSES an AlterField that adds `through=` to an M2M ("Cannot alter
# field ... they are not compatible types"), so the schema change is applied
# by hand, in a safe order for live databases:
#   1. create `players_playerteam` (CreateModel),
#   2. copy every existing membership — for EVERY existing season, so no
#      roster is lost (no season at all -> season-less row, later bound to
#      the first created season),
#   3. drop the old auto-created table `players_player_teams` and flip the
#      migration STATE only (SeparateDatabaseAndState).

from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models


def copy_assignments_to_seasons(apps, schema_editor):
    """One row per (existing membership x existing season) — no data loss."""
    Player = apps.get_model("players", "Player")
    PlayerTeam = apps.get_model("players", "PlayerTeam")
    Season = apps.get_model("matchdays", "Season")
    seasons = list(Season.objects.all())
    rows = []
    for player in Player.objects.prefetch_related("teams"):
        for team in player.teams.all():
            if seasons:
                rows.extend(
                    PlayerTeam(player=player, team=team, season=season) for season in seasons
                )
            else:
                rows.append(PlayerTeam(player=player, team=team, season=None))
    if rows:
        PlayerTeam.objects.bulk_create(rows, ignore_conflicts=True)


def drop_old_m2m_table(apps, schema_editor):
    schema_editor.execute("DROP TABLE players_player_teams")


def recreate_old_m2m_table(apps, schema_editor):
    """Reverse: rebuild the auto-created M2M table (deduped from PlayerTeam)."""
    if schema_editor.connection.vendor == "sqlite":
        ddl = (
            'CREATE TABLE "players_player_teams" ('
            '"id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, '
            '"player_id" bigint NOT NULL REFERENCES "players_player" ("id") '
            "DEFERRABLE INITIALLY DEFERRED, "
            '"team_id" bigint NOT NULL REFERENCES "teams_team" ("id") '
            "DEFERRABLE INITIALLY DEFERRED)"
        )
    else:  # PostgreSQL
        ddl = (
            'CREATE TABLE "players_player_teams" ('
            '"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, '
            '"player_id" bigint NOT NULL REFERENCES "players_player" ("id") '
            "DEFERRABLE INITIALLY DEFERRED, "
            '"team_id" bigint NOT NULL REFERENCES "teams_team" ("id") '
            "DEFERRABLE INITIALLY DEFERRED)"
        )
    schema_editor.execute(ddl)
    schema_editor.execute(
        "INSERT INTO players_player_teams (player_id, team_id) "
        "SELECT DISTINCT player_id, team_id FROM players_playerteam"
    )


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("matchdays", "0002_season_matchday_season"),
        ("players", "0002_alter_player_options_and_more"),
        ("teams", "0001_initial"),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="PlayerTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_assignments",
                        to="players.player",
                        verbose_name="player",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_team_assignments",
                        to="matchdays.season",
                        verbose_name="season",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_assignments",
                        to="teams.team",
                        verbose_name="team",
                    ),
                ),
            ],
            options={
                "verbose_name": "player team assignment",
                "verbose_name_plural": "player team assignments",
                "ordering": ["team__name", "player__name"],
            },
        ),
        migrations.RunPython(copy_assignments_to_seasons, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(drop_old_m2m_table, recreate_old_m2m_table),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="player",
                    name="teams",
                    field=models.ManyToManyField(
                        help_text="A player can belong to multiple teams — per season.",
                        related_name="players",
                        through="players.PlayerTeam",
                        to="teams.team",
                        verbose_name="teams",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="playerteam",
            constraint=models.UniqueConstraint(
                fields=("player", "team", "season"), name="unique_player_team_season"
            ),
        ),
        migrations.AddConstraint(
            model_name="playerteam",
            constraint=models.UniqueConstraint(
                condition=models.Q(("season__isnull", True)),
                fields=("player", "team"),
                name="unique_player_team_without_season",
            ),
        ),
    ]
